# Generated by Django 3.2.20 on 2023-08-16 11:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=80)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.CharField(default='New Table', max_length=10, unique=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-capacity'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('reserved_date', models.DateField()),
                ('reserved_time_slot', models.CharField(choices=[('09:00', '09:00 AM'), ('12:00', '12:00 PM'), ('18:00', '06:00 PM')], default='12:00', max_length=25)),
                ('reservation_status', models.CharField(choices=[('Awaiting confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='awaiting confirmation', max_length=25, unique=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='reservations.customer')),
                ('reserved_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_reserved', to='reservations.table')),
            ],
            options={
                'ordering': ['-reserved_time_slot'],
            },
        ),
    ]
