# Generated by Django 3.2.20 on 2023-08-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20230817_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_count',
            field=models.PositiveIntegerField(choices=[(1, '1 Customer'), (2, '2 Customers'), (3, '3 Customers'), (4, '4 Customers'), (5, '5 Customers'), (6, '6 Customers')], default=2),
        ),
    ]
