# Generated by Django 3.2.20 on 2023-08-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
