# Generated by Django 3.2.20 on 2023-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_table_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_count',
            field=models.PositiveIntegerField(choices=[(2, '2 Customers'), (3, '3 Customers'), (4, '4 Customers'), (5, '5 Customers'), (6, '6 Customers')], default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_time_slot',
            field=models.CharField(choices=[('12:00', '12:00 PM'), ('13:00', '13:00 PM'), ('17:00', '08:00 PM'), ('18:00', '22:00 PM'), ('19:00', '20:00 PM'), ('21:00', '21:00 PM'), ('22:00', '22:00 PM'), ('23:00', '23:00 PM')], default='12:00', max_length=25),
        ),
    ]
