# Generated by Django 3.2.20 on 2023-08-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0007_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_table',
            new_name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_count',
            field=models.IntegerField(choices=[(1, '1 Guest'), (2, '2 Guests'), (3, '3 Guests'), (4, '4 Guests'), (5, '5 Guests'), (6, '6 Guests')], default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('awaiting confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='awaiting confirmation', max_length=25),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('reserved_date', 'reserved_time_slot', 'table')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
