# Generated by Django 3.2.20 on 2023-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_reserved_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_number',
            new_name='table_description',
        ),
    ]
