# Generated by Django 3.2.20 on 2023-08-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='surname',
        ),
    ]
