# Generated by Django 3.2.20 on 2023-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkMenuItem',
            fields=[
                ('drink_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_item_name', models.CharField(max_length=50, unique=True)),
                ('drink_description', models.CharField(max_length=200, unique=True)),
                ('drink_price', models.FloatField()),
                ('drink_item_type', models.IntegerField(choices=[(0, 'Soft'), (1, 'Wine'), (2, 'Beers'), (3, 'AddItem')], default=3)),
                ('drink_available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-drink_available'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenuItem',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item_name', models.CharField(max_length=50, unique=True)),
                ('food_description', models.CharField(max_length=200, unique=True)),
                ('food_price', models.FloatField()),
                ('food_item_type', models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Desserts'), (3, 'AddItem')], default=3)),
                ('food_available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-food_available'],
            },
        ),
    ]
