# Generated by Django 3.2.20 on 2023-08-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='drink_description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='food_description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
