# Generated by Django 3.2.20 on 2023-08-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_drinks', '0002_auto_20230815_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='drink_item_type',
            field=models.IntegerField(choices=[(0, 'Soft'), (1, 'Wine'), (2, 'Beers'), (3, 'AddItem')]),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='food_item_type',
            field=models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Desserts'), (3, 'AddItem')]),
        ),
    ]
