# Generated by Django 3.2.20 on 2023-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_drinks', '0003_auto_20230817_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='drink_item_type',
            field=models.IntegerField(choices=[(0, 'Cocktails'), (1, 'Beers'), (2, 'Rhums'), (3, 'AddItem')]),
        ),
    ]
