# Generated by Django 3.2.20 on 2023-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_drinks', '0004_alter_drinkmenuitem_drink_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='drink_description',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='food_description',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
