# Generated by Django 3.2.20 on 2023-08-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_drinks', '0005_auto_20230825_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='drink_item_type',
            field=models.IntegerField(choices=[(0, 'Cocktails'), (1, 'Beers'), (2, 'Rhums'), (3, 'Zero'), (4, 'AddItem')]),
        ),
    ]
